### ISSUE TITLE
Code Correction 

### ISSUE THREAD

**Issue by pelo99** [brandon-rhodes/fopnp#14]
This is regarding the book on Python3. Found a couple of errors with the code provided in the book. Could not find the code in Github, hence reporting the page numbers in the book.

Page 63:

> > > mysock = server_sock.accept()
> > > addr, port = mysock.getpeername()

accept() method is supposed to return a tuple with the active connection being the first item. accept()[0] should have been used here. Unless you do that, the next statement would report an error. I wonder how the second statement got executed in your code.

Page 90:
 _try:
   host = sock.connect(address)
 except socket.error as e:_

sock.connect() returns a NoneType and yet is being assigned to a variable in here.

**Comment by brandon-rhodes** [comment]
Thank you! I have added the label "Book" to this issue so that, if the book is ever reprinted, I can include this information when the publisher asks for any Errata. I am going to close the issue — because there's nothing, if I understand you correctly, that I can do to the code in this repository to fix it — but be assured that when it's time for a new printing, I'll be searching for even closed issues with the “Book” label, so this one will come up and make it to them. Thanks!
