### ISSUE TITLE
p.23 The "FAKE" Message Didn't Go Through

### ISSUE THREAD

**Issue by paiitseng** [brandon-rhodes/fopnp#15]
Hi Brandon,

I was trying to simulate forging a response from the server by jumping in and sending datagram before the server has a chance to send its own reply. I ran the server on my Macbook terminal, suspended it by Ctrl + Z, ran the client, and then typed in the three code lines on python3. All I got is the 4 returned from sock.sendto but the terminal running client is still waiting for server's response. 
```
=====1st terminal=====
$ python3 p020_udp_local.py server
Listening at ('127.0.0.1', 1060)
^Z
[1]+  Stopped                 python3 p020_udp_local.py server
$

=====2nd terminal=====
$ python3 p020_udp_local.py client
The OS assigned me the address ('0.0.0.0', 56166)

=====3rd terminal=====
$ python3
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import socket
> > > sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
> > > sock.sendto('FAKE'.encode('ascii'), ('127.0.0.1', 37821))
> > > 4
```

**Comment by brandon-rhodes** [comment]
I am not sure why this is not working! On my Linux system, the `sendto()` arrives at the client just fine:

```
$ python udp_local.py client
The OS assigned me the address ('0.0.0.0', 50349)
The server ('127.0.0.1', 43218) replied u'FAKE'
```

It looks tome that the reason is that you are sending to the wrong port. Your client is at port 56166 but, for reasons that I cannot quite discern, you instead send the fake package to port 37821 where probably no one is listening. Make the port numbers match, and that will probably get the example working for you!
