### ISSUE TITLE
Can't launch VM

### ISSUE THREAD

**Issue by simkus9** [brandon-rhodes/fopnp#3]
Failed to open a session for the virtual machine playground-vm.

NamedPipe#0 failed to bind to local socket /home/brandon/.boot2docker/boot2docker-vm.sock (VERR_FILE_NOT_FOUND).

Result Code: NS_ERROR_FAILURE (0x80004005)
Component: Console
Interface: IConsole {8ab7c520-2442-4b66-8d74-4ff1e195d2b6}

**Comment by sjdaigle** [comment]
Same error here, running Network Playground 1.0 (Oct. 25 release) on VirtualBox 4.3.20 r96966 on OS X 10.9.5.

**Comment by brandon-rhodes** [comment]
Thanks for letting me know that you are having the problem too, @sjdaigle! I have been on the road this last month, but should soon be back home and have access to a machine that is much better at spinning up virtual machines than this tiny travel laptop that I carry. (Hmm — though if things work fine, then I guess I will have to try to find a Mac to try the Playground on!)

**Comment by sjdaigle** [comment]
Hi Brandon,

Thanks so much for the follow up email! I am very excited about your book and about the whole concept of simulating the Internet, end users and websites with 12 VMs. I am new to Python but programmed professionally for about 3 years on small projects 20 years ago. Your approach resonated with me so I am looking forward to getting the playground up and running!

Best,

Steve

**Comment by jgoerzen** [comment]
That error can be trivially worked around by disabling the serial port in the VM config.  However, the bigger issue is that the included disk image is not actually bootable.  It seems to lack a proper bootloader and kernel.

**Comment by jgoerzen** [comment]
It appears that the missing bit here is to download boot2docker.iso from https://github.com/boot2docker/boot2docker/releases and attach it to the VM config before booting the VM, as the VMDK does not contain an OS.  That fixes it!

**Comment by ghost** [comment]
Any further movement on this issue?  Excited to get the playground up and running on OSX.  I have boot2docker and the playground 1.0 ova, but the system does not start properly and generates the same errors.

**Comment by ghost** [comment]
So how do you fix this issue then?

**Comment by brandon-rhodes** [comment]
All right!

After months of trying to work around this problem — and after several conversations with people who have more experience with virtualization than I do — I have deprecated my original scheme of distributing a bare VirtualBox image and expecting it to run across multiple operating systems correctly, especially with network forwarding turned on.

I have just rebuilt, repackaged, and re-uploaded the Playground as a Vagrant box, because Vagrant had a reputation for doing a better job of supporting cross-platform image support than do any of the raw native back-end mechanisms for virtualization like VirtualBox.

I have amended the Playground instructions to explain starting up a Vagrant box:

https://github.com/brandon-rhodes/fopnp/tree/m/playground

Could you try out the instructions and let me know if they work on your platform and, if not, at which step they fail? Thanks so much!

**Comment by ghost** [comment]
I have this working on the first try, on OS X 10.10.5, Vagrant 1.7.2, Virtualbox 4.3.30.  All example commands in the README file were executed and returned the expected results.

**Comment by brandon-rhodes** [comment]
WONDERFUL! Sorry that this took so long, everyone — virtualization across multiple platforms is not my specialty and it was a bit of reach for me to have tried this in the first place. I am going to close this particular issue, but please open a new one if the new scheme fails for you, including the error message so that I can try tackling it — thanks!
