### ISSUE TITLE
How to connect to playground

### ISSUE THREAD

**Issue by michealbeatty** [brandon-rhodes/fopnp#5]
I've got the playground-VM running but I don't see how to connect to it. The instructions just say to use SSH but no info on an address to connect to. I've tried to guess at the proper address based on the information in the README but have had no luck. Am i missing something or are the instructions just that vague?

**Comment by brandon-rhodes** [comment]
I am not sure, from your description, how far you have progressed in the instructions, but every `ssh` command that I see in the README includes the complete command line including the hostname. Here are all four of them:

```
$ ssh -p 2201 brandon@localhost
$ ssh root@www
$ ssh h1
$ ssh -p 2022 docker@localhost
```

Is the command that is giving you trouble one of these? Or does the README mention another ssh command that it fails to spell out or cite? If so, please quote the sentence you are reading so that I know how far down the README you have made it so far. Thanks!

**Comment by michealbeatty** [comment]
Re-reading the README, I understand now what you were saying. For some reason I thought the `brandon@localhost` was just an example and that it should be replaced with something else. I guess my frustration really was born out of the fact that I am unable to connect to the playground and I just assumed I was misunderstanding the instructions.

I still can't connect to the playground but it has nothing to do with this issue.
Thanks.

**Comment by brandon-rhodes** [comment]
All right!

After months of trying to work around this problem — and after several conversations with people who have more experience with virtualization than I do — I have deprecated my original scheme of distributing a bare VirtualBox image and expecting it to run across multiple operating systems correctly, especially with network forwarding turned on.

I have just rebuilt, repackaged, and re-uploaded the Playground as a Vagrant box, because Vagrant had a reputation for doing a better job of supporting cross-platform image support than do any of the raw native back-end mechanisms for virtualization like VirtualBox.

I have amended the Playground instructions to explain starting up a Vagrant box:

https://github.com/brandon-rhodes/fopnp/tree/m/playground

Could you try out the instructions and let me know if they work on your platform and, if not, at which step they fail? Thanks so much!
