### ISSUE TITLE
Unable to properly start the image on a windows host

### ISSUE THREAD

**Issue by tomkregenbild** [brandon-rhodes/fopnp#6]
I am using Virtualbox in order to run the playground on a windows 8.1 machine.
I downloaded the image, imported and started it and I do see that I get my machine to listen on forwarded ports. When I connect using Putty (localhost:2201) I just get a black screen, it is not disconnecting but I am unable to do anything on these ports. 

When I look at the console in virtualbox I just see a black screen, seems like the OS is not starting and nothing is really happening.

Can you suggest what to do?

**Comment by tomkregenbild** [comment]
Checked it also on windows 7 with virtual box and the result was the same

**Comment by brandon-rhodes** [comment]
All right!

After months of trying to work around this problem — and after several conversations with people who have more experience with virtualization than I do — I have deprecated my original scheme of distributing a bare VirtualBox image and expecting it to run across multiple operating systems correctly, especially with network forwarding turned on.

I have just rebuilt, repackaged, and re-uploaded the Playground as a Vagrant box, because Vagrant had a reputation for doing a better job of supporting cross-platform image support than do any of the raw native back-end mechanisms for virtualization like VirtualBox.

I have amended the Playground instructions to explain starting up a Vagrant box:

https://github.com/brandon-rhodes/fopnp/tree/m/playground

Could you try out the instructions and let me know if they work on your platform and, if not, at which step they fail? Thanks so much!

**Comment by tomkregenbild** [comment]
Thanks a lot, I'll check it as soon I'll some spare time. Really appreciate it.

**Comment by brandon-rhodes** [comment]
Please feel free to re-open this issue if you have further problems. Thanks!
