### ISSUE TITLE
errors starting vm on windows 7

### ISSUE THREAD

**Issue by fractal76** [brandon-rhodes/fopnp#7]
```
c:> .\VBoxHeadless.exe --startvm playground-vm
```

Error:

```
Error: failed to start machine. 
Error message: NamedPipe#0 failed to create named pipe 
\home\brandon\.boot2docker\boot2docker-vm.sock (VERR_INVALID_NAME)
```

**Comment by brandon-rhodes** [comment]
All right!

After months of trying to work around this problem — and after several conversations with people who have more experience with virtualization than I do — I have deprecated my original scheme of distributing a bare VirtualBox image and expecting it to run across multiple operating systems correctly, especially with network forwarding turned on.

I have just rebuilt, repackaged, and re-uploaded the Playground as a Vagrant box, because Vagrant had a reputation for doing a better job of supporting cross-platform image support than do any of the raw native back-end mechanisms for virtualization like VirtualBox.

I have amended the Playground instructions to explain starting up a Vagrant box:

https://github.com/brandon-rhodes/fopnp/tree/m/playground

Could you try out the instructions and let me know if they work on your platform and, if not, at which step they fail? Thanks so much!
